import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";
import FloatingContact from "@/shared/FloatingContact";


export const metadata: Metadata = {
  title: "Fujian Acceesories Co. LTD",
  description: "Generated by fujian Acceesories Co. LTD",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FloatingContact/>
        <Navbar/> 
         {children}
         <Footer/>
         </body>
    </html>
  );
}
